#!/usr/bin/env python3
"""Build the static GitHub Pages artifact from ``web/``."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the CD Monitor GitHub Pages site")
    parser.add_argument("--source", default="web")
    parser.add_argument("--dest", default="_site")
    parser.add_argument("--api-base", default="")
    args = parser.parse_args()
    source = Path(args.source).resolve()
    dest = Path(args.dest).resolve()
    if not (source / "index.html").is_file():
        parser.error(f"missing frontend source: {source / 'index.html'}")
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(source, dest)
    runtime = dest / "runtime-config.js"
    runtime.write_text(
        "// Generated by scripts/build_pages.py; do not put secrets here.\n"
        "window.CD_MONITOR_CONFIG = {\n"
        f"  apiBase: {json.dumps(args.api_base.strip().rstrip('/'))},\n"
        "  accessToken: \"\",\n"
        "};\n",
        encoding="utf-8",
    )
    # GitHub Pages must not run Jekyll over the copied assets.
    (dest / ".nojekyll").write_text("", encoding="utf-8")
    print(f"Built {dest} (apiBase={args.api_base.strip().rstrip('/') or 'same-origin'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
